### ISSUE TITLE
Crash with health overlay

### ISSUE THREAD

**Issue by martmists** [Ladysnake/Requiem#173]
```
[20:54:04] [main/INFO]: [STDERR]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector substituteHealth(Lnet/minecraft/class_1657;)F in mixins.requiem.client.json:compat.healthoverlay.HealthRendererMixin failed injection check, (0/1) succeeded. Scanned 2 target(s). Using refmap requiem-refmap.json
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[20:54:04] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[20:54:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
[20:54:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[20:54:04] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[20:54:04] [main/INFO]: [STDERR]: 	at net.minecraft.class_329.handler$zhi000$render(class_329.java:1811)
[20:54:04] [main/INFO]: [STDERR]: 	at net.minecraft.class_329.method_1760(class_329.java:828)
[20:54:04] [main/INFO]: [STDERR]: 	at net.minecraft.class_329.method_1753(class_329.java:203)
[20:54:04] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:585)
[20:54:04] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:947)
[20:54:04] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:585)
[20:54:04] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:202)
[20:54:04] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:54:04] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:54:04] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:54:04] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:54:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
[20:54:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
[20:54:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[20:54:04] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:54:04] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:54:04] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:54:04] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:54:04] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[20:54:04] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[20:54:04] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:54:04] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:54:04] [main/FATAL]: Unreported exception thrown!
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.7.3+build.176.jar:0.8+build.17+unknown-b17.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) ~[fabric-loader-0.7.3+build.176.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) ~[fabric-loader-0.7.3+build.176.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	at net.minecraft.class_329.handler$zhi000$render(class_329.java:1811) ~[intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.class_329.method_1760(class_329.java:828) ~[intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:203) ~[intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:585) ~[intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:947) ~[intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:585) [intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:202) [intermediary-minecraft-1.15.1-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.3+build.176.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.3+build.176.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.3+build.176.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector substituteHealth(Lnet/minecraft/class_1657;)F in mixins.requiem.client.json:compat.healthoverlay.HealthRendererMixin failed injection check, (0/1) succeeded. Scanned 2 target(s). Using refmap requiem-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344) ~[sponge-mixin-0.8+build.17.jar:0.8+build.17+unknown-b17.git-unknown]
	... 28 more
```

**Comment by ranenvious** [comment]
I am also having this issue but not with health overlay, I don't actually know what mine is interacting with
