### ISSUE TITLE
Attempting to activate the Mod results in a fatal error

### ISSUE THREAD

**Issue by AGuyInTheInternet** [Ladysnake/Requiem#232]
ok this is my first time using github, please be patient! 
so, in the first death, after selecting "Make me a demon already" and activate the mod content, the game just crashes, i hope this help:
org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_3324::method_14556(Lnet/minecraft/class_3222;Z)Lnet/minecraft/class_3222; has incompatible changes at opcode 135 in callback net/minecraft/class_3324::soulbound$respawnPlayer.
Expected: [Lnet/minecraft/class_2338;, Z, Lnet/minecraft/class_3218;, Ljava/util/Optional;, Lnet/minecraft/class_3225;, Lnet/minecraft/class_3218;, Lnet/minecraft/class_3222;]
   Found: [Lnet/minecraft/class_2338;, F, Z, Lnet/minecraft/class_3218;, Ljava/util/Optional;, Lnet/minecraft/class_3225;, Lnet/minecraft/class_3218;]
	at net.minecraft.class_3324.handler$bmk000$soulbound$respawnPlayer$missing(class_3324.java)
	at net.minecraft.class_3324.method_14556(class_3324.java:494)
	at net.minecraft.class_3244.method_12068(class_3244.java:1342)
	at net.minecraft.class_2799.method_12120(class_2799.java:30)
	at net.minecraft.class_2799.method_11054(class_2799.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_2600$$Lambda$6322/1842129868.run(Unknown Source)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$5573/210369914.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

please, i need help!

**Comment by Pyrofab** [comment]
So I assume you used the wrong version of Requiem ?
For the next time, I'd suggest uploading the whole crash report somewhere like [gist.github.com](https://gist.github.com/), it lets us get all the information while avoiding making the issue itself too long.
