### ISSUE TITLE
When in ghost form, anyone who looks at me (including myself if I go in f5) will crash. Why is this?

### ISSUE THREAD

**Issue by YTSeanPlays** [Ladysnake/Requiem#234]
I do not know why this happens, but when someone is in ghost form, they crash when seen. 
This is the crash report:

[19:22:49] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at io.github.apace100.origins.networking.ModPacketsC2S.lambda$null$0(ModPacketsC2S.java:36) ~[Origins-1.16.4-0.4.6.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_281]
	at io.github.apace100.origins.networking.ModPacketsC2S.lambda$null$1(ModPacketsC2S.java:36) ~[Origins-1.16.4-0.4.6.jar:?]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_281]
	at io.github.apace100.origins.networking.ModPacketsC2S.lambda$null$2(ModPacketsC2S.java:35) ~[Origins-1.16.4-0.4.6.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[19:22:49] [main/INFO]: [CHAT] YTSeanPlays has made the advancement [A devilish conundrum]
[19:22:49] [main/INFO]: Loaded 7 advancements
[19:23:01] [Server thread/INFO]: Stopping server
[19:23:01] [Server thread/INFO]: Saving players
[19:23:01] [Server thread/INFO]: Saving worlds
[19:23:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[CLASSES]'/minecraft:overworld
[19:23:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (CLASSES): All chunks are saved
[19:23:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[CLASSES]'/minecraft:the_nether
[19:23:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:23:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[CLASSES]'/minecraft:the_end
[19:23:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:23:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (CLASSES): All chunks are saved
[19:23:07] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:23:07] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:23:07] [main/FATAL]: Reported exception thrown!

**Comment by Pyrofab** [comment]
Not sure what's happening, this looks like an issue in Origins somehow.

**Comment by Pyrofab** [comment]
Well, I don't think we can do much about it, and I haven't heard any confirmation that it happens on latest Origins, so I'll close this issue. Feel free to reopen with an updated report if it still happens.
