### ISSUE TITLE
Crash when dying with crimson moon

### ISSUE THREAD

**Issue by Tanden22** [Ladysnake/Requiem#254]
hey, i've got a weird crash whenever i die, and i can't figure out why. any advice?

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_284.method_1303(class_284.java:460)
	at net.minecraft.class_284.method_1300(class_284.java:448)
	at net.minecraft.class_280.method_1277(class_280.java:313)
	at net.minecraft.class_283.method_1293(class_283.java:77)
	at net.minecraft.class_279.method_1258(class_279.java:332)
	at ladysnake.satin.impl.ResettableManagedShaderEffect.render(ResettableManagedShaderEffect.java:112)
	at ladysnake.requiem.client.ZaWorldFx.renderShaderEffects(ZaWorldFx.java:136)
	at ladysnake.satin.api.event.ShaderEffectRenderCallback.lambda$null$0(ShaderEffectRenderCallback.java:31)
	at ladysnake.satin.api.event.ShaderEffectRenderCallback$$Lambda$5611/1450341843.renderShaderEffects(Unknown Source)
	at net.minecraft.class_757.handler$did000$hookShaderRender(class_757.java:8472)
	at net.minecraft.class_757.method_3192(class_757.java:555)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1364913072.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

**Comment by Tanden22** [comment]
This was solved over on the discord. If you're having the same problems, try removing the "Crimson Moon" mod if it's installed

**Comment by Pyrofab** [comment]
This can be fixed by manually installing an adequate version of Satin
