### ISSUE TITLE
Crash with optifine

### ISSUE THREAD

**Issue by theoparis** [Ladysnake/Requiem#262]
This is may or may not be because of optifabric, but I am getting a crash with the following mods installed on 1.16.5 with the latest fabric api...

## Mods
![image](https://user-images.githubusercontent.com/11761863/112696520-39497300-8e43-11eb-99c0-f6e060392bb1.png)

## Crash

```
[14:52:12] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2248)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:501)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:425)
	at net.minecraft.client.main.Main.main(Main.java:135)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method forceOverlayWhenIntangible(Lnet/minecraft/class_4587;Lnet/minecraft/class_4184;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.requiem.client.json:remnant.GameRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap requiem-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 30 more
Exiting with -1
Process exited with code 255.

```

**Comment by Pyrofab** [comment]
definitely optifine, requiem doesn't launch with it.

**Comment by Merith-TK** [comment]
why the "will not fix" label?

**Comment by Pyrofab** [comment]
Optifine has multiple issues with multiple dependencies, and spending time on fixing them when 1.17 is coming soon and is breaking all rendering anyway seems like a waste of time.

**Comment by Merith-TK** [comment]
You know what? that is fair, what even is the issue? as far as i know requiem wouldnt render anything that could break it? 

Also could you at the very least, add a "conflicts with" inside the `fabric.mod.json` so that people arnt just crashed without any information.

**Comment by Pyrofab** [comment]
Oh yes, good point I should document the conflict in the mod metadata. And I'm not even sure of why optifine crashes with requiem myself, as it crashes too early to get a crash report. I know at least there is another issue with [Satin](https://github.com/Ladysnake/Satin) that prevents the use of shaders, so that's at least 2 rather annoying issues to fix before requiem can work with optifine.

**Comment by Merith-TK** [comment]
I could hook it up to a debugger if you like? just tell me the commit ID for the latest release and i will clone and see if i can get logs from Intellij

**Comment by Pyrofab** [comment]
I add tags for every release, so you can take the 1.5.1 tag if you want. That said, I can't promise I'll fix the issue myself if you do find where it comes from.
