### ISSUE TITLE
Wandering Spirit crashes the game when possessing a mob

### ISSUE THREAD

**Issue by FumpleWumper** [Ladysnake/Requiem#281]
I've installed the latest Requiem version as well as have Origins up-to-date, when picking Demon > Wandering Spirit > Nitwit (from classes) the game freezes and crashes, giving me the following crash report below

How can I fix this?

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 02/05/21 19:57
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraft.class_1921.method_23033()Lnet/minecraft/class_293$class_5596;
	at ladysnake.satin.impl.RenderLayerDuplicator.copy(RenderLayerDuplicator.java:86)
	at ladysnake.satin.impl.RenderLayerSupplier.getRenderLayer(RenderLayerSupplier.java:47)
	at ladysnake.satin.impl.FramebufferWrapper.getRenderLayer(FramebufferWrapper.java:107)
	at ladysnake.requiem.client.RequiemFx.getZoomFx(RequiemFx.java:188)
	at net.minecraft.class_922.localvar$cga000$requiem$replaceRenderLayer(class_922.java:1582)
	at net.minecraft.class_922.method_4054(class_922.java:130)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ladysnake.satin.impl.RenderLayerDuplicator.copy(RenderLayerDuplicator.java:86)
	at ladysnake.satin.impl.RenderLayerSupplier.getRenderLayer(RenderLayerSupplier.java:47)
	at ladysnake.satin.impl.FramebufferWrapper.getRenderLayer(FramebufferWrapper.java:107)
	at ladysnake.requiem.client.RequiemFx.getZoomFx(RequiemFx.java:188)
	at net.minecraft.class_922.localvar$cga000$requiem$replaceRenderLayer(class_922.java:1582)
	at net.minecraft.class_922.method_4054(class_922.java:130)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)

-- Entity being rendered --
Details:
	Entity Type: minecraft:skeleton (net.minecraft.class_1613)
	Entity ID: 368
	Entity Name: Skeleton
	Entity's Exact location: -1452.69, 72.00, -349.03
	Entity's Block location: World: (-1453,72,-350), Chunk: (at 3,4,2 in -91,-22; contains blocks -1456,0,-352 to -1441,255,-337), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Entity's Momentum: 0.00, -0.06, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_946@3bdf07fb
	Location: 0.31,-1.62,-0.61 - World: (0,-2,-1), Chunk: (at 0,-1,15 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: -165.9375
	Delta: 0.88001645
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)

**Comment by Pyrofab** [comment]
I see 2 possibilities:
- You may be using an older version of minecraft, in which case you should try 1.16.5
- You may be using a wrong Satin version, in which case you should manually install this: https://www.curseforge.com/minecraft/mc-mods/satin-api/files/3070595

**Comment by FumpleWumper** [comment]
Ah, I was lacking the updated Satin version! Installing it has fixed the problem, thank you so much for your attention!
