### ISSUE TITLE
configure to can posses an enderman and your game crashes

### ISSUE THREAD

**Issue by ruan128** [Ladysnake/Requiem#305]
i try posses an enderman with configuration and my game crashes pls fix

**Comment by Pyrofab** [comment]
Err, could you share the crash report ?

**Comment by ruan128** [comment]
ok

**Comment by ruan128** [comment]
is T launcher so ima send 2 images

**Comment by ruan128** [comment]
and is only on the end dimension

**Comment by ruan128** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/83889748/117840770-d8d78f00-b252-11eb-8468-cf9803cce37d.png)
![Screenshot_4](https://user-images.githubusercontent.com/83889748/117840798-dc6b1600-b252-11eb-8c07-17a0b0472425.png)

**Comment by ruan128** [comment]
erro desconhecido= unknow error

**Comment by SekoiaTree** [comment]
that doesn't help us; you need to send the file at C:\Users\Pichau\AppData\Roaming\.minecraft\crash-reports\crash-2021-05-11_12.16.11-server.txt

**Comment by ruan128** [comment]
ok im gonna send it just copying and pasting the whole text cuz too big for screen shot

**Comment by ruan128** [comment]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 14/05/21 18:41
Description: Ticking entity

java.lang.IllegalStateException: Removing entity while ticking!
	at net.minecraft.class_3218.method_18774(class_3218.java:942)
	at net.minecraft.class_3218.method_18770(class_3218.java:958)
	at net.minecraft.class_3222.method_5731(class_3222.java:670)
	at ladysnake.requiem.common.remnant.BasePossessionHandlers.handleEndermanPossession(BasePossessionHandlers.java:101)
	at ladysnake.requiem.api.v1.event.requiem.PossessionStartCallback.lambda$static$0(PossessionStartCallback.java:58)
	at ladysnake.requiem.common.impl.possession.PossessionComponentImpl.startPossessing(PossessionComponentImpl.java:101)
	at ladysnake.requiem.api.v1.possession.PossessionComponent.startPossessing(PossessionComponent.java:82)
	at ladysnake.requiem.common.entity.ability.SoulPossessAbility.onCooldownEnd(SoulPossessAbility.java:100)
	at ladysnake.requiem.common.entity.ability.AbilityBase.setCooldown(AbilityBase.java:68)
	at ladysnake.requiem.common.entity.ability.AbilityBase.update(AbilityBase.java:105)
	at ladysnake.requiem.common.impl.ability.ImmutableMobAbilityController.tick(ImmutableMobAbilityController.java:104)
	at ladysnake.requiem.common.impl.ability.PlayerAbilityController.tick(PlayerAbilityController.java:176)
	at dev.onyxstudios.cca.api.v3.component.tick.CommonTickingComponent.serverTick(CommonTickingComponent.java:48)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickComponents(Unknown Source)
	at net.minecraft.class_3218.handler$bce000$tick(class_3218.java:3075)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3218.method_18774(class_3218.java:942)
	at net.minecraft.class_3218.method_18770(class_3218.java:958)
	at net.minecraft.class_3222.method_5731(class_3222.java:670)
	at ladysnake.requiem.common.remnant.BasePossessionHandlers.handleEndermanPossession(BasePossessionHandlers.java:101)
	at ladysnake.requiem.api.v1.event.requiem.PossessionStartCallback.lambda$static$0(PossessionStartCallback.java:58)
	at ladysnake.requiem.common.impl.possession.PossessionComponentImpl.startPossessing(PossessionComponentImpl.java:101)
	at ladysnake.requiem.api.v1.possession.PossessionComponent.startPossessing(PossessionComponent.java:82)
	at ladysnake.requiem.common.entity.ability.SoulPossessAbility.onCooldownEnd(SoulPossessAbility.java:100)
	at ladysnake.requiem.common.entity.ability.AbilityBase.setCooldown(AbilityBase.java:68)
	at ladysnake.requiem.common.entity.ability.AbilityBase.update(AbilityBase.java:105)
	at ladysnake.requiem.common.impl.ability.ImmutableMobAbilityController.tick(ImmutableMobAbilityController.java:104)
	at ladysnake.requiem.common.impl.ability.PlayerAbilityController.tick(PlayerAbilityController.java:176)
	at dev.onyxstudios.cca.api.v3.component.tick.CommonTickingComponent.serverTick(CommonTickingComponent.java:48)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickComponents(Unknown Source)
	at net.minecraft.class_3218.handler$bce000$tick(class_3218.java:3075)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 4
	Entity Name: Ruan1
	Entity's Exact location: 101.94, 59.25, -26.95
	Entity's Block location: World: (101,59,-27), Chunk: (at 5,3,5 in 6,-2; contains blocks 96,0,-32 to 111,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Ruan1'/4, l='ServerLevel[requiem]', x=101.94, y=59.25, z=-26.95]]
	Chunk stats: ServerChunkCache: 1829
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (240,4,160), Chunk: (at 0,0,0 in 15,10; contains blocks 240,0,160 to 255,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 115985 game time, 13000 day time
	Level name: requiem
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 16967 (now: false), thunder time: 62022 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5123182032 bytes (4885 MB) / 5872025600 bytes (5600 MB) up to 5872025600 bytes (5600 MB)
	CPUs: 8
	JVM Flags: 10 total; -Xmn128M -Xmx5591M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
		fabric: Fabric API 0.34.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.2+d6244c6d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.16.9
		pehkui: Pehkui 2.1.0+21w18a
		playerabilitylib: Pal 1.2.1
		requiem: Requiem 1.6.3
		requiemapi: Requiem-API 1.6.3
		satin: Satin 1.5.1
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
	Player Count: 1 / 8; [class_3222['Ruan1'/4, l='ServerLevel[requiem]', x=101.94, y=59.25, z=-26.95]]
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
