### ISSUE TITLE
incompatibility with slime origin

### ISSUE THREAD

**Issue by ElectroBoi** [Ladysnake/Requiem#356]
Crash Report

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 6/14/21 3:54 PM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field virtuoel.pehkui.api.PehkuiConfig.DATA from class net.minecraft.class_1309
	at net.minecraft.class_1309.revertScale(class_1309.java:11359)
	at net.minecraft.class_1309.handler$zpb000$tryUseTotem(class_1309.java:11377)
	at net.minecraft.class_1309.method_6095(class_1309.java)
	at net.minecraft.class_1309.method_5643(class_1309.java:1101)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:631)
	at net.minecraft.class_1309.method_5768(class_1309.java:250)
	at net.minecraft.class_3075.method_13430(class_3075.java:32)
	at net.minecraft.class_3075.method_13431(class_3075.java:25)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at net.minecraft.class_2170.method_9249(class_2170.java:249)
	at net.minecraft.class_3244.method_14370(class_3244.java:1211)
	at net.minecraft.class_3244.method_31286(class_3244.java:1198)
	at net.minecraft.class_3244.method_12048(class_3244.java:1177)
	at net.minecraft.class_2797.method_12115(class_2797.java:36)
	at net.minecraft.class_2797.method_11054(class_2797.java:9)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1000924312 bytes (954 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 2
	JVM Flags: 11 total; -Xms3G -Xmx3G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch
	Fabric Mods: 
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		chime: Chime 1.1.3
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.11.26
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		extraorigins: Extra Origins 1.16.5-12
		fabric: Fabric API 0.35.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+731c05f37d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fiber: fiber 0.23.0-2
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lithium: Lithium 0.6.6
		locki: Locki 0.2.0
		login: Login 1.0.0
		minecraft: Minecraft 1.16.5
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.0
		pehkui: Pehkui 2.2.0+21w20a
		playerabilitylib: Pal 1.2.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		requiem: Requiem 1.7.12
		requiemapi: Requiem-API 1.7.12
		slimeorigin: Slimeorigin 2.1.0
		spark: spark 1.6.0
	Player Count: 2 / 20; [class_3222['Zhafran123'/266, l='ServerLevel[world]', x=-107.76, y=79.00, z=-302.84], class_3222['indgamer5'/3071, l='ServerLevel[world]', x=-112.44, y=79.00, z=-302.50]]
	Data Packs: vanilla (incompatible), Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

Server Log

[15:54:03] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalAccessError: tried to access field virtuoel.pehkui.api.PehkuiConfig.DATA from class net.minecraft.class_1309
	at net.minecraft.class_1309.revertScale(class_1309.java:11359) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.handler$zpb000$tryUseTotem(class_1309.java:11377) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_6095(class_1309.java) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1101) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5643(class_1657.java:914) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_5643(class_3222.java:631) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5768(class_1309.java:250) ~[intermediary-server.jar:?]
	at net.minecraft.class_3075.method_13430(class_3075.java:32) ~[intermediary-server.jar:?]
	at net.minecraft.class_3075.method_13431(class_3075.java:25) ~[intermediary-server.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[intermediary-server.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[intermediary-server.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:249) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1211) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_31286(class_3244.java:1198) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1177) ~[intermediary-server.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:36) ~[intermediary-server.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:9) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[15:54:03] [Server thread/ERROR]: This crash report has been saved to: C:\Users\PetraJanice\Desktop\MINECRAFT SERVERS\GRSMP Moded S1\.\crash-reports\crash-2021-06-14_15.54.03-server.txt
[15:54:03] [Server thread/INFO]: Stopping server

**Comment by ElectroBoi** [comment]
i have origin slime on, apperently when i died as a slime the server crashed

**Comment by James103** [comment]
Does the same crash also occur if you run `/kill @s` instead of `/kill @e`? If so, then it definitely has to do with the player itself dying.

**Comment by ElectroBoi** [comment]
yes both of that commands makes the server crash, sorry for the slow reply

**Comment by Pyrofab** [comment]
Does this happen without requiem ?

**Comment by ElectroBoi** [comment]
it Happened when I have requiem and slime origin on

**Comment by James103** [comment]
Have you tried disabling or removing Requiem from your mod folder, then restarting and reproducing this issue?

**Comment by ElectroBoi** [comment]
> Have you tried disabling or removing Requiem from your mod folder, then restarting and reproducing this issue?

yes I have tried that, I removed requiem while having slime on, and removed slime while having requiem on, right now my server doesn't have slime origin on

**Comment by PsychoBreadstick** [comment]
Slime origin hasn’t been updated in two years. This issue is no longer relevant.
