### ISSUE TITLE
Missing dynamic registry crash

### ISSUE THREAD

**Issue by marcohoovy** [Ladysnake/Requiem#398]
full error:
`java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / requiem:requiem/dialogues]
    at net.minecraft.class_5455.method_30534(class_5455.java:52) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
    at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
    at net.minecraft.class_5455.method_30530(class_5455.java:52) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
    at ladysnake.requiem.common.dialogue.DialogueRegistryImpl.startDialogue(DialogueRegistryImpl.java:54) ~[requiem-2.0.0-alpha.10.jar:?]
    at ladysnake.requiem.common.dialogue.PlayerDialogueTracker.startDialogue(PlayerDialogueTracker.java:72) ~[requiem-2.0.0-alpha.10.jar:?]
    at ladysnake.requiem.client.RequiemClientListener.onEndTick(RequiemClientListener.java:164) ~[requiem-2.0.0-alpha.10.jar:?]
    at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65) ~[4fd9132c-d72b-4e97-9d2b-f6b614a13517.jar:?]
    at net.minecraft.class_310.handler$cdd000$onEndTick(class_310.java:11573) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
    at net.minecraft.class_310.method_1574(class_310.java:1806) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
    at net.minecraft.class_310.method_1523(class_310.java:1081) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
    at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]`

System details:
OS: arch linux
mc version: 1.17.1

**Comment by Pyrofab** [comment]
Err, how did that happen ? Is this on a multiplayer server ?

**Comment by Pyrofab** [comment]
Turns out this was Fabric API's fault. You should be able to fix it by updating to Fabric API 0.39 or later.
