### ISSUE TITLE
Game crashes as soon as origin selections pops up

### ISSUE THREAD

**Issue by jakubkubik98** [Ladysnake/Requiem#455]
Fresh new world.

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/3/21, 8:34 AM
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.getReturnValueZ()" because "cir" is null
	at net.minecraft.class_1657.handler$dng000$requiem$canClimb(class_1657.java:20010)
	at net.minecraft.class_1309.method_6101(class_1309.java:1490)
	at net.minecraft.class_1309.method_18801(class_1309.java:2268)
	at net.minecraft.class_1309.method_26318(class_1309.java:2243)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_1657.method_6091(class_1657.java:1591)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1657.method_6007(class_1657.java:559)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_3222.method_14226(class_3222.java:466)
	at net.minecraft.class_3244.method_18784(class_3244.java:212)
	at net.minecraft.class_2535.method_10754(class_2535.java:238)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1657.handler$dng000$requiem$canClimb(class_1657.java:20010)
	at net.minecraft.class_1309.method_6101(class_1309.java:1490)
	at net.minecraft.class_1309.method_18801(class_1309.java:2268)
	at net.minecraft.class_1309.method_26318(class_1309.java:2243)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_1657.method_6091(class_1657.java:1591)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1657.method_6007(class_1657.java:559)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 109
	Entity Name: MrHishprung
	Entity's Exact location: 252.50, 65.00, 152.50
	Entity's Block location: World: (252,65,152), Section: (at 12,1,8 in 15,4,9; chunk contains blocks 240,0,144 to 255,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:466)
	at net.minecraft.class_3244.method_18784(class_3244.java:212)
	at net.minecraft.class_2535.method_10754(class_2535.java:238)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 914252856 bytes (871 MiB) / 3120562176 bytes (2976 MiB) up to 11005853696 bytes (10496 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1500X Quad-Core Processor          
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.07
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.07
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32193.43
	Virtual memory used (MB): 21036.41
	Swap memory total (MB): 15856.53
	Swap memory used (MB): 1270.01
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10496m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.3
		additionalbars: Additional Bars 2.1.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.4.1
		amecsapi: Amecs API 1.1.5+mc21w16a
		annotateddi: Annotated DI 2.0.4+1.17.1
		aopalliance_aopalliance: aopalliance 1.0
		apoli: Apoli 2.0.5
		aqupdcaracal: Caracal mob 1.17-1.3.2
		arcanus: Arcanus 1.22
		architectury: Architectury 2.6.35
		artifality: Artifality 0.4.2
		assembly: Assembly 21w06a-1.0.0
		automatone: Automatone 0.4.1
		axolotlitemfix: Axolotl Item Fix 1.1.3
		backslot: BackSlot 1.2.2
		backslotaddon: BackSlot Addon 1.0.7
		bclib: BCLib 0.4.4
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.12.1-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterrecipebook: Better Recipe Book 1.5.4
		betterthirdperson: Better Third Person 1.5.0
		blur: Blur (Fabric) 2.4.0
		boatcontainer: BoatContainer 1.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		caelus: Caelus API 0.0.18-1.17.1
		calio: Calio 1.3.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.1
		charmonium: Charmonium 3.3.0
		chime: Chime 1.2.0-SNAPSHOT
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-1.1.2
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_google_inject_guice: guice 5.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		controlling: Controlling For Fabric 1.1.2
		cosmetica: Cosmetica 0.2.0
		couplings: Couplings 1.5.0+1.17
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		deepslatecutting: Deepslate Cutting 1.2.2
		desolation: Desolation 1.1.5
		ditn: Deep In The Night 0.1.2
		dragonloot: DragonLoot 1.0.9
		drippyloadingscreen: Drippy Loading Screen 1.3.0
		earthtojavamobs: Earth2Java 1.7.3+1.17
		eldritch_mobs: Eldritch Mobs 1.9.6
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		endgoblintraders: End Goblin Traders 1.2.1
		endrem: End Remastered 4.1.0
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		enhancedcelestials: Enhanced Celestials 2.0.5
		extended_armor_bars: Extended Armor Bars 1.1.0
		extraalchemy: Extra Alchemy 1.6.1
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.12.2
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.1
		fireplacelib: Fireplace Lib 6.2.0+1.17.1
		flesh2leather: Flesh2Leather 1.0.2
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.21
		geodes: More Geodes 1.0.5
		go-fish: Go Fish 1.3.0-beta-1.17.1
		goblintraders: Goblin Traders 1.2.0
		goldenhoppers: Golden Hoppers 1.1.0
		graveyard: The Graveyard 2.0
		grid: Grid 1.17.1-fabric0.36.1-1.6.6
		guild: Guild 0.3.3
		harvest_scythes: Harvest Scythes 2.0.6
		iceberg: Iceberg 1.0.23
		illuminations: Illuminations 1.9
		impaled: Impaled 1.0.1
		impersonate: Impersonate 2.3.5
		infusion_table: Infusion Table 1.0.2
		inmis: Inmis 2.3.2-1.17.1
		inspecio: Inspecio 1.1.0+1.17
		java: OpenJDK 64-Bit Server VM 16
		javax_inject_javax_inject: javax.inject 1
		konkrete: Konkrete 1.3.0
		locki: Locki 0.5.1
		logical_zoom: Logical Zoom 0.0.11
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.17.1
		mcda: MC Dungeons Armors 1.7.15
		mcdar: MC Dungeons Artifacts 1.4.2
		medieval_origins: Medieval Origins 2.2.0
		medievalweapons: Medieval Weapons 1.1.7
		midnightlib: MidnightLib 0.3.0
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.14
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		mythic-mounts: Mythic Mounts 1.17.1-2.0
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		netherite_items: Netherite Items 1.1.0
		npcvariety: NPC Variety 2.2.0
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		origins: Origins 1.1.4
		outvoted: Outvoted 1.5.0-beta.3
		overlord: Overlord 3.0.4+1.17.1
		oxidized: Oxidized 1.4.0
		oxidizelib: OxidizeLib 1.1.0
		playerabilitylib: Pal 1.4.0
		polymorph: Polymorph 0.0.14-1.17.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.5.2+1.17.1
		requiem: Requiem 2.0.0-beta.1
		requiem-core: Requiem-Core 2.0.0-beta.1
		requiemapi: Requiem-API 2.0.0-beta.1
		reroll: Reroll 1.3.0-1.17.1
		roughlyenoughitems: Roughly Enough Items 6.2.335
		roughlyenoughresources: Roughly Enough Resources 2.2.0
		satin: Satin 1.6.4
		seasons: Fabric Seasons 1.3.1-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		shulkerutils: shulkerutils 1.0.4-1.17
		sit: Sit 1.17.1-13
		small_artifacts: Small Artifacts 0.0.3-1.17.1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		the_aether: The Aether 1.17.1-1.5.0
		thonkutil: ThonkUtil 1.2
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		traverse: Traverse 4.0.0
		trinkets: Trinkets 3.0.4
		tweed: Tweed API 3.0.0-beta.22
		upgradedechests: Upgraded Ender Chests 1.0.3-1.17
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.17
		urns: Urns 1.0.1
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.1
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.1.2
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.7.1
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		yungsapi: YUNG's API 1.17-Fabric-19
	Player Count: 1 / 8; [class_3222['MrHishprung'/109, l='ServerLevel[Ded]', x=252.50, y=65.00, z=152.50]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'```

**Comment by jakubkubik98** [comment]
As soon as origin selection pups up, game freezes and Crashes to Desktop

**Comment by jakubkubik98** [comment]
Also tried with Requiem as only mod:

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/3/21, 8:48 AM
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.getReturnValueZ()" because "cir" is null
	at net.minecraft.class_1657.handler$bdh000$requiem$canClimb(class_1657.java:5483)
	at net.minecraft.class_1309.method_6101(class_1309.java:1490)
	at net.minecraft.class_1309.method_18801(class_1309.java:2268)
	at net.minecraft.class_1309.method_26318(class_1309.java:2243)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_1657.method_6091(class_1657.java:1591)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1657.method_6007(class_1657.java:559)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_3222.method_14226(class_3222.java:466)
	at net.minecraft.class_3244.method_18784(class_3244.java:212)
	at net.minecraft.class_2535.method_10754(class_2535.java:238)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1657.handler$bdh000$requiem$canClimb(class_1657.java:5483)
	at net.minecraft.class_1309.method_6101(class_1309.java:1490)
	at net.minecraft.class_1309.method_18801(class_1309.java:2268)
	at net.minecraft.class_1309.method_26318(class_1309.java:2243)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_1657.method_6091(class_1657.java:1591)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1657.method_6007(class_1657.java:559)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 303
	Entity Name: MrHishprung
	Entity's Exact location: 50.50, 67.00, 82.50
	Entity's Block location: World: (50,67,82), Section: (at 2,3,2 in 3,4,5; chunk contains blocks 48,0,80 to 63,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:466)
	at net.minecraft.class_3244.method_18784(class_3244.java:212)
	at net.minecraft.class_2535.method_10754(class_2535.java:238)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 851276216 bytes (811 MiB) / 2013265920 bytes (1920 MiB) up to 11005853696 bytes (10496 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1500X Quad-Core Processor          
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.07
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.07
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32193.43
	Virtual memory used (MB): 20257.91
	Swap memory total (MB): 15856.53
	Swap memory used (MB): 1258.63
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10496m -Xms256m
	Fabric Mods: 
		automatone: Automatone 0.4.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		chime: Chime 1.2.0-SNAPSHOT
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.12.2
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.1
		impersonate: Impersonate 2.3.5
		java: OpenJDK 64-Bit Server VM 16
		locki: Locki 0.5.1
		minecraft: Minecraft 1.17.1
		playerabilitylib: Pal 1.4.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		requiem: Requiem 2.0.0-beta.1
		requiem-core: Requiem-Core 2.0.0-beta.1
		requiemapi: Requiem-API 2.0.0-beta.1
		satin: Satin 1.6.4
	Player Count: 1 / 8; [class_3222['MrHishprung'/303, l='ServerLevel[New World]', x=50.50, y=67.00, z=82.50]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'```

**Comment by Pyrofab** [comment]
Could you try with fabric loader 0.12.5 or up ?

**Comment by jakubkubik98** [comment]
Seems to work normally with 0.12.5

**Comment by Pyrofab** [comment]
Good to hear ^^
