### ISSUE TITLE
`requiem:charged_jump was not registered through mod metadata or plugin`

### ISSUE THREAD

**Issue by SettingDust** [Ladysnake/Requiem#594]
```
org.quiltmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
Caused by: java.lang.ExceptionInInitializerError
	at ladysnake.requiem.common.remnant.BasePossessionHandlers.register(BasePossessionHandlers.java:115)
	at ladysnake.requiem.common.VanillaRequiemPlugin.registerPossessionEventHandlers(VanillaRequiemPlugin.java:317)
	at ladysnake.requiem.common.VanillaRequiemPlugin.onRequiemInitialize(VanillaRequiemPlugin.java:167)
	at ladysnake.requiem.Requiem.registerPlugin(Requiem.java:127)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at ladysnake.requiem.common.ApiInitializer.setPluginCallback(ApiInitializer.java:132)
	at ladysnake.requiem.Requiem.onInitialize(Requiem.java:122)
	at net.minecraft.Bootstrap.handler$epd000$onInitialize(Bootstrap:1542)
	at net.minecraft.Bootstrap.initialize(Bootstrap:69)
	at net.minecraft.client.main.Main.main(Main:161)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:471)
	... 2 more
Caused by: java.lang.IllegalStateException: requiem:charged_jump was not registered through mod metadata or plugin
	at dev.onyxstudios.cca.internal.base.ComponentRegistryImpl.getOrCreate(ComponentRegistryImpl.java:62)
	at dev.onyxstudios.cca.api.v3.component.ComponentRegistry.getOrCreate(ComponentRegistry.java:76)
	at ladysnake.requiem.api.v1.entity.ExternalJumpingMount.<clinit>(ExternalJumpingMount.java:40)
	... 16 more
```

**Comment by Redfan2** [comment]
Is this Issue still existent? If yes, would you be able to post a log of it? If it isn‘t existent anymore, please close it.

**Comment by Pyrofab** [comment]
That doesn't sound possible, everyone should be crashing if this was still an issue
