### ISSUE TITLE
Reqium crashes server on startup.

### ISSUE THREAD

**Issue by Cookieess** [Ladysnake/Requiem#628]
I have tried removing requiem and it starts up fine.

Utils.java:62) ~[quilt-loader-0.18.8.jar:?]... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:178) ~[quilt-loader-0.18.8.jar:?]at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.18.8.jar:?]at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.18.8.jar:?]at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]at xyz.amymialee.mialeemisc.MialeeMiscConfig.loadConfig(MialeeMiscConfig.java:55) ~[transformed-mod-mialeemisc.i0:0/:?]at xyz.amymialee.mialeemisc.MialeeMisc.onInitialize(MialeeMisc.java:48) ~[transformed-mod-mialeemisc.i0:0/:?]at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.18.8.jar:?]at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.18.8.jar:?]at org.quiltmc.loader.impl.entrypoint.EntrypointUtil s.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.18.8.jar:?]... 16 more

**Comment by Redfan2** [comment]
Are you playing with other mods except Requiem? If yes, would you provide a log or crash report?
